services:
  localstack:
    image: localstack/localstack
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
      - SERVICES=s3
      - DEFAULT_REGION=us-east-1
    ports:
      - "4566:4566"
      - "4510-4559:4510-4559" # Port range for various LocalStack services
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
